In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
np.insert(arr, 1, 10)

array([ 1, 10,  2,  3])

In [5]:
arr #Arrays numpy tem tamanho fixo. Novo é criado

array([1, 2, 3])

In [6]:
a = np.array([[1,2], [3,4]])

In [9]:
print(a)
print(a.ndim)

[[1 2]
 [3 4]]
2


In [10]:
print(a.sum(axis=0))

[4 6]


In [11]:
print(a.sum())

10


In [15]:
print(a.sum(axis=1))
a

[3 7]


array([[1, 2],
       [3, 4]])

In [13]:
np.insert(a,1,5,axis=1)

array([[1, 5, 2],
       [3, 5, 4]])

In [16]:
np.insert(a,0,5,axis=0)

array([[5, 5],
       [1, 2],
       [3, 4]])

In [21]:
x = np.insert(a,2,5,axis=0)
x

array([[1, 2],
       [3, 4],
       [5, 5]])

In [22]:
#append
a = np.array([1,2,3])
a

array([1, 2, 3])

In [23]:
np.append(a,[4,5,6])

array([1, 2, 3, 4, 5, 6])

In [24]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [25]:
np.append(a,[[5,6]])

array([1, 2, 3, 4, 5, 6])

In [28]:
np.append(a,[[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
#delete
a = np.array([[1,2], [3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
np.delete(a,1, axis=0)

array([[1, 2],
       [5, 6]])

In [32]:
np.delete(a,0,1)

array([[2],
       [4],
       [6]])

In [33]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
np.delete(a,np.s_[::2], axis=0) #s_ usado para slice - fatiamento

array([[ 4,  5,  6],
       [10, 11, 12]])

In [38]:
np.delete(a,np.s_[::2], axis=1)

array([[ 2],
       [ 5],
       [ 8],
       [11]])

In [39]:
#Repetindo elementos
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [40]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [42]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [43]:
np.repeat(a,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [44]:
np.repeat(a,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [45]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [47]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [48]:
np.tile(a,2)

array([1, 2, 3, 1, 2, 3])

In [49]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [51]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [53]:
np.tile(b,2) #Não tem parametro para o eixo

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [54]:
#DIvidindo Arrays
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
np.array_split(a,2,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [56]:
np.array_split(a,2,axis=1)

[array([[1, 2],
        [4, 5]]), array([[3],
        [6]])]

In [58]:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arrays = np.array_split(b,3,axis=0)

In [60]:
for x in arrays:
    print(x)

[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [61]:
arrays = np.array_split(b,2,axis=0)

In [62]:
for x in arrays:
    print(x)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [63]:
print(arrays)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [65]:
#Criando arrays de 0 e 1
np.zeros(2)

array([ 0.,  0.])

In [68]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [72]:
a = np.ones((10,10))
a

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [74]:
type((5,5))
a.shape

(10, 10)

In [78]:
np.identity(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [79]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [81]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [83]:
a[a>6]

array([7, 8, 9])

In [85]:
idx = a>2

In [86]:
idx

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [94]:
a = np.array([[1,2], [3,4]])
b = np.array([[6,7]])

In [95]:
a

array([[1, 2],
       [3, 4]])

In [96]:
b

array([[6, 7]])

In [97]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [6, 7]])

In [99]:
np.concatenate((a,b.transpose()),axis=1)

array([[1, 2, 6],
       [3, 4, 7]])

In [101]:
b.T #transpose

array([[6],
       [7]])

In [102]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.random.shuffle(a) #Embaralhando array

In [105]:
a

array([6, 5, 0, 3, 4, 2, 8, 7, 9, 1])

In [106]:
#Números complexos
a = np.array([1,10 + 2j, 20+5j])

In [107]:
a

array([  1.+0.j,  10.+2.j,  20.+5.j])

In [109]:
a[1]

(10+2j)

In [110]:
a[2]

(20+5j)

In [111]:
a[1] + a[2]

(30+7j)

In [112]:
a[1]*a[2]

(190+90j)

In [114]:
np.arange(1,100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [116]:
np.linspace(2.0, 3.0, 5) #Uniformemente espaçados

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [117]:
np.linspace(2, 2.5, 5)

array([ 2.   ,  2.125,  2.25 ,  2.375,  2.5  ])

In [187]:
np.round((np.random.sample()*10))

0.0

In [189]:
a = np.array([[1,2], [2,3], [4,5] ,[5,6]])
a

array([[1, 2],
       [2, 3],
       [4, 5],
       [5, 6]])

In [190]:
np.unique(a)

array([1, 2, 3, 4, 5, 6])