In [3]:
mat = [[5,4,7], [0,3,4], [0,0,6]]
for x in mat:
    print(x)

[5, 4, 7]
[0, 3, 4]
[0, 0, 6]


In [9]:
print(mat[-1])
print(mat[1][1])
[linha[1] for linha in mat]

[0, 0, 6]
3


[4, 3, 0]

In [23]:
import numpy as np

In [24]:
joao_pts = [20,30,40,15]
maria_pts = [100,24,48,23]
jose_pts = [92,22,34,12]
chico_pts = [12,34,12,43]

pontos = np.array([joao_pts, maria_pts, jose_pts, chico_pts])

In [26]:
pontos[1]

array([100,  24,  48,  23])

In [28]:
pontos[1][0]

100

In [31]:
my_data = np.arange(0,20)
print(my_data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [33]:
mat1 = np.reshape(my_data, (5,4))
mat1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [36]:
mat1[2][2]

10

In [37]:
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [39]:
pontos.item(5)

24

In [41]:
m1 = ['python', 'eh', 'legal']
m2 = ['guido', 'van', 'rossum']
m3 = [10,20,30]
[m1, m2, m3]

[['python', 'eh', 'legal'], ['guido', 'van', 'rossum'], [10, 20, 30]]

In [46]:
np.array([m1,m2,m3])

array([['python', 'eh', 'legal'],
       ['guido', 'van', 'rossum'],
       ['10', '20', '30']],
      dtype='<U6')

In [48]:
m1 = np.array([[1,2,3], [4,5,6]])
m2 = np.array([[7,8,9], [10,11,12]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [52]:
m2 / m1

array([[ 7. ,  4. ,  3. ],
       [ 2.5,  2.2,  2. ]])

In [54]:
np.matrix.round(m2/m1)

array([[ 7.,  4.,  3.],
       [ 2.,  2.,  2.]])

In [55]:
10 * m2

array([[ 70,  80,  90],
       [100, 110, 120]])

In [57]:
m1+5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [58]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [59]:
m2 - 1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
m1 * m2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [63]:
m1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])