In [2]:
import numpy

In [5]:
a = numpy.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [7]:
type(a)

numpy.ndarray

In [10]:
mat = numpy.array([[1,2], [3,4]])
mat

array([[1, 2],
       [3, 4]])

In [19]:
print(mat[1][1])
print(mat[-1][-1])
print(mat[0,:])
print(mat[:,0])
print(mat[1,0])

4
4
[1 2]
[1 3]
3


In [22]:
print(mat)
print(mat.transpose())

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [24]:
m1 = numpy.array([[1,2],[3,4]])
m2 = numpy.array([[5,6],[7,8]])
m1+m2

array([[ 6,  8],
       [10, 12]])

In [26]:
m1*m2

array([[ 5, 12],
       [21, 32]])

In [31]:
m3 = numpy.array([1,2,3,4])
print(m3.sum())
print(m3.argmax()) #índice do maior valor do array
print(m3.argmin()) #índice do menor valor do array

10
3
0


In [ ]:
#Numpy array é mais eficiente que list do Python, além de várias funcionalidades
